---
- name: exercise 121
  hosts: ansible2
  vars:
    my_package: virt-manager
  tasks:
    - name: install package
      yum:
        name: "{{ my_package }}"
        state: present
    - name: gather facts on installed packages
      package_facts:
        manager: auto
    - name: show facts on package {{ my_package }}
      debug:
        var: ansible_facts.packages[my_package]
      when: my_package in ansible_facts.packages