---
- hosts: ansible2
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
    selinux_fcontexts:
      - { target: '/web(./*)?', setype: 'httpd_sys_content_t', ftype: 'd' }
    selinux_restore_dirs:
      - /web

  tasks:
    - name: create dir
      file:
        path: /web
        state: directory
    - name: execute the role and catch errors
      block:
      - include_role:
          name: linux-system-roles.selinux
      rescue:
        - name: handle errors
          fail:
            msg: "role failed"
          when: not selinux_reboot_required
        - name: restart managed host
          shell: sleep 2 && shutdown -r now "Ansible updates triggered"
          async: 1
          poll: 0
          ignore_errors: true
        - name: wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300
        - name: reapply the role
          include_role:
            name: linux-system-roles.selinux
