---
- name: define configuration for control node in homelab
  hosts: homelab1
  tasks:
    - name: install wanted tools
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ control_packages }}"
    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ control_services }}"
    - name: run jenkins podman container
      containers.podman.podman_container:
        image: docker.io/jenkins/jenkins
        name: jenkins
        restart_policy: on-failure
        state: started
        privileged: false
        detach: true
        publish:
          - 8080:8080
          - 50000:50000
        volume: jenkins_home:/var/jenkins_home
        hostname: jenkins
    - name: pull smee client docker image
      containers.podman.podman_image:
        name: docker.io/deltaprojects/smee-client:latest
        pull: true
        state: present
    - name: run smee client
      shell: podman run -d --name proxy docker.io/deltaprojects/smee-client:latest -u https://smee.io/UDJIVI1ieSdxx2B -t http://cjohnhelms.ddns.net:8080/github-webhook/


