---
- name: working with custom facts
  hosts: all
  tasks:
    - name: make dir
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: copy files
      copy:
        src: vars/custom.fact
        dest: /etc/ansible/facts.d
    - name: install services
      yum:
        name: "{{ ansible_facts['ansible_local']['custom']['packages']['samba_package'] }}"
        state: latest
      when: ansible_facts['ansible_local']['custom'] is defined
    - name: start and enable service
      service:
        name: "{{ ansible_facts['ansible_local']['custom']['services']['samba_service'] }}"
        state: started
        enabled: true
      when: ansible_facts['ansible_local']['custom'] is defined