---
- name: install and start webserver using facts
  hosts: ansible1
  tasks:
  - name: install package
    yum:
      name: "{{ ansible_facts['ansible_local']['exercise61']['software']['package'] }}"
      state: latest
  - name: start the service
    service:
      name: "{{ ansible_facts['ansible_local']['exercise61']['software']['service'] }}"
      state: "{{ ansible_facts['ansible_local']['exercise61']['software']['state'] }}"
      enabled: "{{ ansible_facts['ansible_local']['exercise61']['software']['enabled'] }}"
      
