---
- name: copy custom facts
  hosts: ansible1
  tasks:
  - name: create custom facts directory
    file: 
      state: directory
      recurse: yes
      path: /etc/ansible/facts.d
  - name: copy custom facts
    copy:
      src: /home/ansible/git/rhce/base/custom_facts/exercise61.fact
      dest: /etc/ansible/facts.d
