---
- name: stat module test
  hosts: ansible1
  tasks:

  - name: stat
    stat:
      path: /etc/hosts
    register: st

  - name: show current values
    debug:
      msg: current value of the st variable is {{ st }}

  - name: test perms
    fail:
      msg: "unexpected file mode, should be set to 0640"
    when: st.stat.mode != '0640'
