---
- name: modifying file
  hosts: all
  tasks:
  
  - name: ensure /tmp/hosts exists
    file:
      path: /tmp/hosts
      state: touch
  
  - name: add some lines to /tmp/hosts
    blockinfile:
      path: /tmp/hosts
      block: |
        192.168.4.110 host1
        192.168.4.120 host2
      state: present
