---
- name: setup httpd
  hosts: ansible1
  tasks:
    - name: install htppd
      yum:
        name: httpd
        state: latest
    - name: install firewalld
      yum:
        name: firewalld
        state: latest
    - name: httpd service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: allow firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
    - name: create index.html
      copy:
        content: "welcome to ansible1"
        dest: /var/www/html/index.html