---
- name: setup a service
  hosts: ansible2
  tasks:
    - name: include the services task file
      include_tasks: tasks/services.yml
      vars:
        package: httpd
        service: httpd
      when: ansible_facts['os_family'] == 'RedHat'
    - name: import firewall file
      import_tasks: tasks/firewall.yml
      vars:
        firewall_package: firewalld
        firewall_service: firewalld
        firewall_rules:
          - http
          - https
